### ISSUE TITLE
Migration Error: Attempting to add a like option to my posts.

### ISSUE THREAD

**Issue by allgooda** [allgooda/project_2#1]
1. User Story:  As a user I want to be able to 'like' other users posts.
2.  ![](https://i.imgur.com/vWqnKlf.png)
3. I have tried asking other students and TA's but have been getting different suggestions from everyone. I've tried googling answers. 
   http://stackoverflow.com/questions/7874330/rake-aborted-table-users-already-exists
   Thank You! Please help!

**Comment by tambling** [comment]
It's right there in the error: you've already created the `likes` table. First, check that there's only one migration that creates `likes`. If there is, you can run `rake db:reset` drop and recreate the database.

**Comment by ghost** [comment]
:+1: 

> **check that there's only one migration that creates `likes`**
